<?php

namespace Database\Seeders\Book;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    public function run()
    {
        // داده‌های نمونه برای جدول books
        $books = [
            [
                'title' => 'کتاب مطالبه‌گری',
                'publisher_id' => 1,
                'publication_year' => '۱۴۰۱',
                'original_price' => 45000,
                'discounted_price' => 40000,
                'introduction' => 'شازده کوچولو کتابی است که توسط آنتوان دو سنت اگزوپری نوشته شده و به مفاهیم عمیق انسانی می‌پردازد.',
                'recommended_audience' => 'این کتاب برای تمام سنین، به ویژه علاقه‌مندان به ادبیات و فلسفه توصیه می‌شود.',
                'excerpt' => 'همه بزرگ‌سالان ابتدا کودک بوده‌اند، اما تعداد کمی از آن‌ها این را به یاد می‌آورند.',
                'sample_file' => 'http://example.com/sample1.pdf',
                'file' => 'http://example.com/book1.pdf',
                'type' => 1,
                'file_type' => 1,
                'page_count' => 96,
                'duration' => null,
                'file_size' => 1024000,
                'publication_status' => 'published',
                'image' => 'مطالبه-گری.jpg',
                'rating' => 4.8,
                'rating_count' => 500,
                'view_count' => 10000,
                'lang' => 'fa',
                'status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'کتاب وحدت و انسجام اجتماعی',
                'publisher_id' => 2,
                'publication_year' => '۱۴۰۰',
                'original_price' => 60000,
                'discounted_price' => 55000,
                'introduction' => 'رمانی از گابریل گارسیا مارکز که به عنوان یکی از شاهکارهای ادبیات جهان شناخته می‌شود.',
                'recommended_audience' => 'این کتاب برای علاقه‌مندان به رمان‌های کلاسیک و ادبیات آمریکای لاتین توصیه می‌شود.',
                'excerpt' => 'سال‌ها بعد، مقابل جوخه‌ی اعدام، سرهنگ آئورلیانو بوئندیا بعدازظهر دوردستی را به یاد می‌آورد که پدرش او را برای کشف یخ برد.',
                'sample_file' => 'http://example.com/sample2.pdf',
                'file' => 'http://example.com/book2.pdf',
                'type' => 1,
                'file_type' => 1,
                'page_count' => 417,
                'duration' => null,
                'file_size' => 2048000,
                'publication_status' => 'published',
                'image' => 'وحدت-و-انسجام-اجتماعی.jpg',
                'rating' => 4.7,
                'rating_count' => 700,
                'view_count' => 15000,
                'lang' => 'fa',
                'status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'کتاب درآمدی بر سیر تاریخی امر به معروف',
                'publisher_id' => 3,
                'publication_year' => '۱۴۰۲',
                'original_price' => 70000,
                'discounted_price' => 65000,
                'introduction' => 'کتابی از رولف دوبلی که به بررسی خطاهای شناختی و نحوه تفکر شفاف می‌پردازد.',
                'recommended_audience' => 'این کتاب برای علاقه‌مندان به روانشناسی و توسعه فردی توصیه می‌شود.',
                'excerpt' => 'ما اغلب فکر می‌کنیم که تصمیم‌هایمان منطقی هستند، اما در واقع تحت تأثیر خطاهای شناختی قرار داریم.',
                'sample_file' => 'http://example.com/sample3.mp3',
                'file' => 'http://example.com/book3.mp3',
                'type' => 'audio',
                'file_type' => 'MP3',
                'page_count' => null,
                'duration' => 14400, // 4 ساعت
                'file_size' => 512000,
                'publication_status' => 'published',
                'image' => 'درآمدی-بر-سیر-تاریخی-امر-به-معروف.jpg',
                'rating' => 4.6,
                'rating_count' => 300,
                'view_count' => 8000,
                'lang' => 'fa',
                'status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'کتاب امر به معروف و نهی از منکر در اندیشه بزرگان- آیت الله خامنه‌ای',
                'publisher_id' => 4,
                'publication_year' => '۱۳۹۹',
                'original_price' => 55000,
                'discounted_price' => 50000,
                'introduction' => 'رمانی از جورج اورول که به بررسی جامعه‌ای توتالیتر و کنترل‌شده می‌پردازد.',
                'recommended_audience' => 'این کتاب برای علاقه‌مندان به ادبیات ضدآرمان‌شهری و فلسفه سیاسی توصیه می‌شود.',
                'excerpt' => 'جنگ صلح است، آزادی بردگی است، نادانی قدرت است.',
                'sample_file' => 'http://example.com/sample4.pdf',
                'file' => 'http://example.com/book4.pdf',
                'type' => 1,
                'file_type' => 1,
                'page_count' => 328,
                'duration' => null,
                'file_size' => 1536000,
                'publication_status' => 'published',
                'image' => 'امر-به-معروف-و-نهی-از-منکر-در-اندیشه-بزرگان-آیت-الله-خامنه_ای-.jpg',
                'rating' => 4.9,
                'rating_count' => 1000,
                'view_count' => 20000,
                'lang' => 'fa',
                'status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'title' => 'کتاب آموزش ملی امر به معروف و نهی از منکر؛ کتاب دوم',
                'publisher_id' => 5,
                'publication_year' => '۱۴۰۱',
                'original_price' => 48000,
                'discounted_price' => 43000,
                'introduction' => 'کتابی از ویکتور فرانکل که به تجربیات او در اردوگاه کار اجباری و معنای زندگی می‌پردازد.',
                'recommended_audience' => 'این کتاب برای علاقه‌مندان به روانشناسی و فلسفه زندگی توصیه می‌شود.',
                'excerpt' => 'هر چیزی را می‌توان از انسان گرفت، به جز یک چیز: آزادی انتخاب نحوه برخورد با شرایط.',
                'sample_file' => 'http://example.com/sample5.pdf',
                'file' => 'http://example.com/book5.pdf',
                'type' => 1,
                'file_type' => 1,
                'page_count' => 200,
                'duration' => null,
                'file_size' => 1024000,
                'publication_status' => 'published',
                'image' => 'آموزش-ملّی-امربه_معروف-و-نهی-از-منکر-تکمیلی.jpg',
                'rating' => 4.8,
                'rating_count' => 600,
                'view_count' => 12000,
                'lang' => 'fa',
                'status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'کتاب اخلاق (متن آموزش اخلاق فردی و اجتماعی)',
                'publisher_id' => 5,
                'publication_year' => '۱۴۰۱',
                'original_price' => 48000,
                'discounted_price' => 43000,
                'introduction' => 'کتابی از ویکتور فرانکل که به تجربیات او در اردوگاه کار اجباری و معنای زندگی می‌پردازد.',
                'recommended_audience' => 'این کتاب برای علاقه‌مندان به روانشناسی و فلسفه زندگی توصیه می‌شود.',
                'excerpt' => 'هر چیزی را می‌توان از انسان گرفت، به جز یک چیز: آزادی انتخاب نحوه برخورد با شرایط.',
                'sample_file' => 'http://example.com/sample5.pdf',
                'file' => 'http://example.com/book5.pdf',
                'type' => 1,
                'file_type' => 1,
                'page_count' => 200,
                'duration' => null,
                'file_size' => 1024000,
                'publication_status' => 'published',
                'image' => 'اخلاق-متن-آموزش-اخلاق-فردی-و-اجتماعی.jpg',
                'rating' => 4.8,
                'rating_count' => 600,
                'view_count' => 12000,
                'lang' => 'fa',
                'status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'کتاب آموزش ملی امر به معروف و نهی از منکر؛ کتاب اول',
                'publisher_id' => 5,
                'publication_year' => '۱۴۰۱',
                'original_price' => 48000,
                'discounted_price' => 43000,
                'introduction' => 'کتابی از ویکتور فرانکل که به تجربیات او در اردوگاه کار اجباری و معنای زندگی می‌پردازد.',
                'recommended_audience' => 'این کتاب برای علاقه‌مندان به روانشناسی و فلسفه زندگی توصیه می‌شود.',
                'excerpt' => 'هر چیزی را می‌توان از انسان گرفت، به جز یک چیز: آزادی انتخاب نحوه برخورد با شرایط.',
                'sample_file' => 'http://example.com/sample5.pdf',
                'file' => 'http://example.com/book5.pdf',
                'type' => 1,
                'file_type' => 1,
                'page_count' => 200,
                'duration' => null,
                'file_size' => 1024000,
                'publication_status' => 'published',
                'image' => 'کتاب-اول-آموزش-ملی-امر-به-معروف-و-نهی-از-منکر.jpg',
                'rating' => 4.8,
                'rating_count' => 600,
                'view_count' => 12000,
                'lang' => 'fa',
                'status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'کتاب درسنامه پیشگیری از جرم',
                'publisher_id' => 5,
                'publication_year' => '۱۴۰۱',
                'original_price' => 48000,
                'discounted_price' => 43000,
                'introduction' => 'کتابی از ویکتور فرانکل که به تجربیات او در اردوگاه کار اجباری و معنای زندگی می‌پردازد.',
                'recommended_audience' => 'این کتاب برای علاقه‌مندان به روانشناسی و فلسفه زندگی توصیه می‌شود.',
                'excerpt' => 'هر چیزی را می‌توان از انسان گرفت، به جز یک چیز: آزادی انتخاب نحوه برخورد با شرایط.',
                'sample_file' => 'http://example.com/sample5.pdf',
                'file' => 'http://example.com/book5.pdf',
                'type' => 1,
                'file_type' => 1,
                'page_count' => 200,
                'duration' => null,
                'file_size' => 1024000,
                'publication_status' => 'published',
                'image' => 'درسنامه-پیشگیری-از-جرم.jpg',
                'rating' => 4.8,
                'rating_count' => 600,
                'view_count' => 12000,
                'lang' => 'fa',
                'status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'title' => 'کتاب احکام لبنیات و فراورده‌های لبنی',
                'publisher_id' => 5,
                'publication_year' => '۱۴۰۱',
                'original_price' => 48000,
                'discounted_price' => 43000,
                'introduction' => 'کتابی از ویکتور فرانکل که به تجربیات او در اردوگاه کار اجباری و معنای زندگی می‌پردازد.',
                'recommended_audience' => 'این کتاب برای علاقه‌مندان به روانشناسی و فلسفه زندگی توصیه می‌شود.',
                'excerpt' => 'هر چیزی را می‌توان از انسان گرفت، به جز یک چیز: آزادی انتخاب نحوه برخورد با شرایط.',
                'sample_file' => 'http://example.com/sample5.pdf',
                'file' => 'http://example.com/book5.pdf',
                'type' => 1,
                'file_type' => 1,
                'page_count' => 200,
                'duration' => null,
                'file_size' => 1024000,
                'publication_status' => 'published',
                'image' => 'لبنیات-و-فرآورده-های-لبنی.jpg',
                'rating' => 4.8,
                'rating_count' => 600,
                'view_count' => 12000,
                'lang' => 'fa',
                'status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'کتاب احکام کشاورزی',
                'publisher_id' => 5,
                'publication_year' => '۱۴۰۱',
                'original_price' => 70000,
                'discounted_price' => 59500,
                'introduction' => 'شناخت و شناساندن وظيفه الهي و ديني هر صنف و ابلاغ احکام صاحبان مشاغل گوناگون، از جمله وظايف مبلغين و محققین در حوزه دين و احکام ديني می‌باشد.
پژوهشکده امربه‌معروف و نهی‌ازمنکر با بهره‌گیری از قرآن و سنت و فقه اهل‌بیت و اخلاق اسلامي و اصول مسلم عقلي به توليد و نشر مجموعه‌ای با عنوان (فقه و زندگي) فعاليت نموده است.',
                'recommended_audience' => 'این کتاب برای علاقه‌مندان به روانشناسی و فلسفه زندگی توصیه می‌شود.',
                'excerpt' => 'هر چیزی را می‌توان از انسان گرفت، به جز یک چیز: آزادی انتخاب نحوه برخورد با شرایط.',
                'sample_file' => 'http://example.com/sample5.pdf',
                'file' => 'http://example.com/book5.pdf',
                'type' => 1,
                'file_type' => 1,
                'page_count' => 200,
                'duration' => null,
                'file_size' => 1024000,
                'publication_status' => 'published',
                'image' => 'کشاورزی.jpg',
                'rating' => 4.8,
                'rating_count' => 600,
                'view_count' => 12000,
                'lang' => 'fa',
                'status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'کتاب احکام قهوه خانه‌ها',
                'publisher_id' => 5,
                'publication_year' => '۱۴۰۱',
                'original_price' => 55000,
                'discounted_price' => 46750,
                'introduction' => 'شناخت و شناساندن وظيفه الهي و ديني هر صنف و ابلاغ احکام صاحبان مشاغل گوناگون، از جمله وظايف مبلغين و محققین در حوزه دين و احکام ديني می‌باشد.
پژوهشکده امربه‌معروف و نهی‌ازمنکر با بهره‌گیری از قرآن و سنت و فقه اهل‌بیت و اخلاق اسلامي و اصول مسلم عقلي به توليد و نشر مجموعه‌ای با عنوان (فقه و زندگي) فعاليت نموده است..',
                'recommended_audience' => 'این کتاب برای علاقه‌مندان به روانشناسی و فلسفه زندگی توصیه می‌شود.',
                'excerpt' => 'هر چیزی را می‌توان از انسان گرفت، به جز یک چیز: آزادی انتخاب نحوه برخورد با شرایط.',
                'sample_file' => 'http://example.com/sample5.pdf',
                'file' => 'http://example.com/book5.pdf',
                'type' => 1,
                'file_type' => 1,
                'page_count' => 200,
                'duration' => null,
                'file_size' => 1024000,
                'publication_status' => 'published',
                'image' => 'قهوه-خانه-ها.jpg',
                'rating' => 4.8,
                'rating_count' => 600,
                'view_count' => 12000,
                'lang' => 'fa',
                'status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'کتاب احکام فرش و تابلوفرش',
                'publisher_id' => 5,
                'publication_year' => '۱۴۰۱',
                'original_price' => 48000,
                'discounted_price' => 40800,
                'introduction' => 'شناخت و شناساندن وظيفه الهي و ديني هر صنف و ابلاغ احکام صاحبان مشاغل گوناگون، از جمله وظايف مبلغين و محققین در حوزه دين و احکام ديني می‌باشد.
پژوهشکده امربه‌معروف و نهی‌ازمنکر با بهره‌گیری از قرآن و سنت و فقه اهل‌بیت و اخلاق اسلامي و اصول مسلم عقلي به توليد و نشر مجموعه‌ای با عنوان (فقه و زندگي) فعاليت نموده است..',
                'recommended_audience' => 'این کتاب برای علاقه‌مندان به روانشناسی و فلسفه زندگی توصیه می‌شود.',
                'excerpt' => 'هر چیزی را می‌توان از انسان گرفت، به جز یک چیز: آزادی انتخاب نحوه برخورد با شرایط.',
                'sample_file' => 'http://example.com/sample5.pdf',
                'file' => 'http://example.com/book5.pdf',
                'type' => 1,
                'file_type' => 1,
                'page_count' => 200,
                'duration' => null,
                'file_size' => 1024000,
                'publication_status' => 'published',
                'image' => 'فرش-و-تابلوفرش.jpg',
                'rating' => 4.8,
                'rating_count' => 600,
                'view_count' => 12000,
                'lang' => 'fa',
                'status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // درج داده‌های نمونه در جدول books
        DB::table('books')->insert($books);
    }
}